on:
  push:
    branches:
      - cata_classic

jobs:
  issue_closer:
    if: github.repository == 'TrinityCore/TrinityCore'
    runs-on: ubuntu-latest
    name: Issue Closer
    steps:
    - name: Issue Closer
      id: issue-closer
      uses: TrinityCore/GitHub-Actions@issue-closer-prod
      with:
        token: ${{ secrets.GITHUB_TOKEN }}